### ISSUE TITLE
Line Chart Display Issue

### ISSUE THREAD

**Issue by Andi24** [krispo/angular-nvd3#188]
Hi,

I'm using the line chart to plot some statistical data ( percentages ) against dates. I pass the dates to the chart as timestamps and I use " d3.time.format('%d/%m')(new Date(d));" to format them into proper looking dates.

The issue I'm facing is that when I use the format, the chart won't display any date, even though it will plot the statistical data. When I don't format dates, as you can see in the photo, it displays but the tooltip works really weird. It only displays for 2 dates, the first and the last, but it displays the last day when I hover over the first day, and vice-versa. Any idea how to fix this?

Any help would be much appreciated! :)
![screenshot](https://cloud.githubusercontent.com/assets/9115624/8953637/da282098-35d7-11e5-9d4d-df8bad62f173.png)

**Comment by Andi24** [comment]
To give you an idea of the hover issue, I uploaded another photo. In it, my cursor is hovered over near the y axis, but the tooltip displays on the far right. The same phenomenon happens with a cumulative line chart, and that's why I moved to the simple one. 
![screen shot 2015-07-29 at 09 48 48 2](https://cloud.githubusercontent.com/assets/9115624/8953646/f725ee1e-35d7-11e5-96c5-5ed3c9d48357.png)

**Comment by krispo** [comment]
Can you show, please,  the code for the options, and what data format are used in dataset. Make sure, that dates are numbers.

**Comment by Andi24** [comment]
```
$scope.options = {
        chart: {
            type: 'lineChart',
            height: 450,
            margin: {
                top: 20,
                right: 20,
                bottom: 40,
                left: 55
            },
            x: function (d) {
                var auxDate = d[0].split('-');
                var newDate = auxDate[0] + "/" + auxDate[1] + "/" + auxDate[2];
                //console.log(new Date(newDate).getTime());
                return new Date(newDate).getTime() * 1000;
            },
            y: function (d) {
                return d[1];
            },
            useInteractiveGuideline: true,
            dispatch: {
                stateChange: function (e) {
                    console.log("stateChange");
                },
                changeState: function (e) {
                    console.log("changeState");
                },
                tooltipShow: function (e) {
                    console.log("tooltipShow");
                },
                tooltipHide: function (e) {
                    console.log("tooltipHide");
                }
            },
            xAxis: {
                axisLabel: 'Days',
                //tickFormat: function(d){
                //    d3.time.format('%d/%m')(new Date(d));
                //}
            },
            yAxis: {
                axisLabel: 'Voltage (v)',
                tickFormat: function (d) {
                    return d3.format('.02f')(d);
                },
                axisLabelDistance: 30
            },
            callback: function (chart) {
                //console.log("!!! lineChart callback !!!");
            }
        }
    };
```

**Comment by Andi24** [comment]
```
[{
      "key": "safari",
      "mean": 56.8079539508111,
      "values": [
        [
          "2015-07-29",
          100.0
        ],
        [
          "2015-07-28",
          98.16849816849816
        ],
        [
          "2015-07-27",
          99.48717948717949
        ],
        [
          "2015-07-26",
          0
        ],
        [
          "2015-07-25",
          0
        ],
        [
          "2015-07-24",
          100.0
        ],
        [
          "2015-07-23",
          0
        ]
      ]
    },
    {
      "key": "ios",
      "mean": 27.66439909297052,
      "values": [
        [
          "2015-07-29",
          100.0
        ],
        [
          "2015-07-28",
          93.65079365079364
        ],
        [
          "2015-07-27",
          0
        ],
        [
          "2015-07-26",
          0
        ],
        [
          "2015-07-25",
          0
        ],
        [
          "2015-07-24",
          0
        ],
        [
          "2015-07-23",
          0
        ]
      ]
    }]
```

**Comment by Andi24** [comment]
Please note that I convert the dates to a timestamp in the x field of the options object. I can provide what the timestamps look like if needed.

**Comment by krispo** [comment]
Try to use this options instead:
```
x: function(d){ 
    return d3.time.format('%Y-%m-%d').parse(d[0]);
},
xAxis: {
    tickFormat: function(d){
        return d3.time.format('%d/%m')(new Date(d));
    }
}
```

**Comment by Andi24** [comment]
The dates display ok, but the hover is still buggy.

![screen shot 2015-07-29 at 11 45 31 2](https://cloud.githubusercontent.com/assets/9115624/8955760/9b423b24-35e7-11e5-95fd-f0f04e5a1665.png)

**Comment by krispo** [comment]
Do you use the latest version of nvd3 and directive?

**Comment by Andi24** [comment]
Shouldn't these provide the latest versions?
 <script src="https://rawgit.com/novus/nvd3/v1.1.15-beta/nv.d3.min.js"></script>
 <script src="https://rawgit.com/krispo/angular-nvd3/v0.1.1/dist/angular-nvd3.js"></script>

**Comment by krispo** [comment]
Ohh, no, currently the latest versions are:
    
    <link rel="stylesheet" href="https://rawgit.com/novus/nvd3/v1.8.1/build/nv.d3.min.css"/>
    <script src="https://rawgit.com/novus/nvd3/v1.8.1/build/nv.d3.min.js"></script>
    <script src="https://rawgit.com/krispo/angular-nvd3/v1.0.0-rc.2/dist/angular-nvd3.js"></script>

**Comment by Andi24** [comment]
I changed the versions but that didn't solve the line chart issue.

On the other hand, my line + bar chart with focus isn't displaying now. This is the error I'm getting.
```
TypeError: nv.models[options.chart.type] is not a function
    at Object.link.scope.api.updateWithOptions (angular-nvd3.js:59)
    at Object.link.scope.api.refresh (angular-nvd3.js:39)
    at Object.<anonymous> (angular-nvd3.js:321)
    at Object.fn (angular-nvd3.js:369)
    at Scope.$get.Scope.$digest (angular.js:14389)
    at Scope.$get.Scope.$apply (angular.js:14652)
    at done (angular.js:9734)
    at completeRequest (angular.js:9924)
    at XMLHttpRequest.requestLoaded (angular.js:9865)
```

**Comment by krispo** [comment]
For the latest version, tooltips work fine on online examples and plunker. So it's strange...

Chart type for line + bar chart with focus in the latest nvd3 version should be changed to:

    chart: {
        type: 'linePlusBarChart'
    }

**Comment by Andi24** [comment]
Alright, the line plus bar chart issue is fixed. I'll keep you posted if I find out what the issue is. 

Any hunch what the cause could be though? I could send you sample data to try and replicate it.

**Comment by Andi24** [comment]
Is it possible to override the hover function for it maybe?

**Comment by bennettatoms** [comment]
Hi, I tried to import the code from your plunker for the box-plot chart directly into my app (after having done the same with a couple other visualizations, without issue), but I'm getting the same error that Andi24 mentioned above:
`TypeError: nv.models[options.chart.type] is not a function
    at Object.link.scope.api.updateWithOptions (angular-nvd3.js:59)
    at Object.link.scope.api.refresh (angular-nvd3.js:39)
    at Object.<anonymous> (angular-nvd3.js:321)
    at Object.fn (angular-nvd3.js:369)
    at Scope.parent.$get.Scope.$digest (angular.js:15685)
    at Scope.parent.$get.Scope.$apply (angular.js:15953)
    at done (angular.js:10366)
    at completeRequest (angular.js:10538)
    at XMLHttpRequest.requestLoaded (angular.js:10479)`

I am using angular 1.4.2 and angular-nvd3 1.0.2. Any idea as to what might be the issue, or if there's a workaround? Thanks!

**Comment by krispo** [comment]
Hi @bennettatoms, check please that in your case the type should be `boxPlotChart`

**Comment by bennettatoms** [comment]
Hi, @krispo, thanks for responding. Yes, in my case I am trying to use type `boxPlotChart`, and that appears to be the chart that's triggering the error.

**Comment by krispo** [comment]
that's weird... maybe, can you create a demo with this issue, or put some code?

**Comment by bennettatoms** [comment]
So, I bower installed angular-nvd3 1.0.2 in the widget I was building, but my app's index.html was referring to a 1.0.0 version. And the d3 version I was using was 3.4.13, so when I updated it to 3.5.6 and updated the angular-nvd3 version referred to in the index, it seemed to take care of the issue. Sorry for the trouble!

**Comment by csworen** [comment]
I'm getting this issue as well, using Angular 1.4.5, angular-nvd3 1.0.2, nvd3 1.8.1, and d3 3.5.6. I'm not sure which chart is throwing it (since we have 5 on one page and 10 in the other). The types we're using are lineChart, scatterPlusLineChart, multiBarHorizontalChart, pieChart, and multiBarChart. I'm guessing it's either not pieChart, since that's the only one not in both of the pages. The error looks exactly the same in both cases:

![angular-nvd3 chart error](https://cloud.githubusercontent.com/assets/8992391/10179337/2b0243be-66ba-11e5-89b3-0cb529affcd0.png)

Let me know if some code would help. Since there's so much of it, I didn't want to severely flood this thread.

**Comment by krispo** [comment]
Just change `scatterPlusLineChart` to `scatterChart`. In the newest nvd3 version it's renamed. If you want to add lines to scatter chart, you add `slope` and `intercept` properties into data.

**Comment by anilkanike** [comment]
Hi Krispo, 

I'm using line chart to display real time JVM statistics and the graph really going crazy. However, when I refresh the browser, the results would be fine... I dont know the reason I spent whole day but no luck... The code that i'm using is: 

function ChartController(scope, interval, dashboardService, TCSA_SYSTEM_INFO_URI) {

```
var chartVm = this;
var refreshInterval = 5 * 1000;

var systemCpuLoadData = [];

// variables for threads data
var daemonThreadCountData = [];
var activeThreadCountData = [];

// variables for classes data
var totalLoadedClassCountData = [];
var unloadedClassCountData = [];

// variables for heap data
var heapUsedData = [];
var heapAvailableData = [];

init();

function init() {
    getSystemInfo();
}

function getSystemInfo() {

    dashboardService.getServerResponse(TCSA_SYSTEM_INFO_URI).then(function (response) {
        chartVm.systemInfo = angular.copy(response.data);
        if (!angular.isUndefined(chartVm.systemInfo)) {
            buildGraphData(chartVm.systemInfo);

        }
    })
}

interval(getSystemInfo, refreshInterval);

function buildGraphData(systemInfo) {

    if (!isEmpty(systemInfo.cpuStatses)) {
        systemInfo.cpuStatses.forEach(function (cpu) {
            systemCpuLoadData.push({x: cpu.dateTime, y: cpu.systemCpuLoad});
        })
    }
    if (!isEmpty(systemInfo.threadsStatses)) {

        systemInfo.threadsStatses.forEach(function (thread) {
            daemonThreadCountData.push({x: thread.dateTime, y: thread.daemonThreadCount});
            activeThreadCountData.push({x: thread.dateTime, y: thread.activeThreadCount});
        })
    }
    if (!isEmpty(systemInfo.classesStatses)) {

        systemInfo.classesStatses.forEach(function (thread) {
            totalLoadedClassCountData.push({x: thread.dateTime, y: thread.totalLoadedClassCount});
            unloadedClassCountData.push({x: thread.dateTime, y: thread.unloadedClassCount});
        })
    }
    if (!isEmpty(systemInfo.memoryStatses)) {

        systemInfo.memoryStatses.forEach(function (thread) {
            heapUsedData.push({x: thread.dateTime, y: thread.heapUsed});
            heapAvailableData.push({x: thread.dateTime, y: thread.heapAvailable});
        })
    }
}

function isEmpty(array) {

    if (typeof array === 'object' && array instanceof Array) {
        if (array && array.length) {
            return false;
        }
    }
    return true;
}

function getChartOptions(xFormat, yFormat, from, to) {

    return {
        chart: {
            //type: 'stackedAreaChart',
            type: 'lineChart',
            height: 450,
            margin: {
                top: 20,
                right: 20,
                bottom: 50,
                left: 65
            },
            x: function (d) {
                return d.x;
            },
            y: function (d) {
                return d.y;
            },
            useVoronoi: false,
            clipEdge: true,
            duration: 100,
            useInteractiveGuideline: true,
            stacked: true,
            showControls: false,
            xAxis: {
                showMaxMin: false,
                tickFormat: function (d) {
                    return d3.time.format(xFormat)(new Date(d))
                }
            },
            forceY: to > 0 ? [from, to] : [],
            yAxis: {
                tickFormat: function (d) {
                    if (yFormat === '') {
                        return d;
                    }
                    return d3.format(yFormat)(d);
                }
            },
        }
    };
}


   scope.cpuOptions = getChartOptions('%I:%M', ',.1%', 0, 1);
    scope.cpuData = updateCPUData();
    function updateCPUData() {
        var cpu = [];
        cpu = systemCpuLoadData;
        //Line chart data should be sent as an array of series objects.
        return [
            {
                "values": cpu,   //values - represents the array of {x,y} data points
                "key": 'CPU Usage',       //key  - the name of the series.
                "color": '#FF7F0E',       //color - optional: choose your own line color.
                mean: 70
            }
        ];
    };
```

**Comment by tusharwalzade216** [comment]
I am also having the same issue as @csworen mentioned 
![image](https://user-images.githubusercontent.com/14350437/27416084-ce16952c-5728-11e7-9f57-5582cf44db3c.png)
in this - 'lineWithFisheyeChart'

**Comment by patrickmcd121** [comment]
I'm having same issue as @Andi24 , with the behaviour of the tool tips, when I use dates for the x-axis. Was this issue ever resolved? I tried swapping chart type to `linePlusBarChart` but still no success
