### ISSUE TITLE
Add support for a new version of nvd3 (1.8.1)

### ISSUE THREAD

**Issue by NameFILIP** [krispo/angular-nvd3#151]
A new version of nvd3 (1.8.1) was released https://github.com/novus/nvd3#changelog
The changelog says "Tooltips were refactored". 
Angular-nvd3 throws "nv.tooltip.cleanup is not a function" error.

**Comment by stefan-schweiger** [comment]
+1 because they added boxplots and candlesticks

**Comment by stefan-schweiger** [comment]
I've only tested it with boxplot, but it seems that it's acutally not that hard to get angular-nvd3 working with nvd3 1.8.1.

The only line I had to change was this:

```js
// before
nv.tooltip.cleanup();

// after
if (typeof nv.tooltip.cleanup == 'function')
    nv.tooltip.cleanup();
```

Here is a working Plunker:
http://plnkr.co/edit/9IJfv8RitHPaBfWOsoep

**Comment by Bluerise** [comment]
Would be nice if this workaround could be committed/published.

**Comment by NameFILIP** [comment]
Fixed in https://github.com/krispo/angular-nvd3/pull/166
